project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!*.rmd"
page-layout: custom
execute:
  echo: false
  eval: true
website:
  title: "Kathryn Q Grace"
  favicon: images/favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - teaching.qmd
      - publications.qmd
      - href: cv.pdf
        text: CV
resources: cv.pdf
format:
  html:
    theme: 
      - pulse
      - styles.scss
    toc: true


